select * from SCRUMTEAM;

--adding new column
ALTER TABLE SCRUMTEAM ADD Salary Integer;

UPDATE SCRUMTEAM SET SALARY=20000 WHERE EMP_ID=2;

UPDATE SCRUMTEAM SET SALARY=15000 WHERE EMP_ID=3;

UPDATE SCRUMTEAM SET SALARY=20000 WHERE EMP_ID=4;

UPDATE SCRUMTEAM SET SALARY=10000 WHERE EMP_ID=5;

UPDATE SCRUMTEAM SET SALARY=25000 WHERE EMP_ID=6;

COMMIT;

--RENAME THE COLUMN
ALTER TABLE SCRUMTEAM RENAME COLUMN SALARY TO Annual_Salary;

COMMIT;

--DELETE OR DROP THE COLUMN
ALTER TABLE SCRUMTEAM DROP COLUMN ANNUAL_SALARY;

--HOW TO CHANGE TABLE NAME?
ALTER TABLE SCRUMTEAM RENAME TO AgileTeam;

select * from AGILETEAM;

commit;

---truncate if we want to delete all data from table but still keep table structure
TRUNCATE TABLE AGILETEAM;

--IF WE WANT TO DELETE THE TABLE AND DATA TOGETHER
DROP TABLE AGILETEAM;